// <auto-generated />
using System;
using FastFoodShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122141149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodShop.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("FastFoodShop.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenDanhMuc = "Burger",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenDanhMuc = "Pizza",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenDanhMuc = "Đồ uống",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            TenDanhMuc = "Combo",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("FastFoodShop.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("FastFoodShop.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("FastFoodShop.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LaCombo")
                        .HasColumnType("bit");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanhMucId = 1,
                            Gia = 45000m,
                            GiaGiam = 39000m,
                            LaCombo = false,
                            SoLuongTon = 100,
                            TenSanPham = "Burger Bò Phô Mai",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            DanhMucId = 2,
                            Gia = 120000m,
                            LaCombo = false,
                            SoLuongTon = 100,
                            TenSanPham = "Pizza Hải Sản",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            DanhMucId = 4,
                            Gia = 250000m,
                            GiaGiam = 199000m,
                            LaCombo = true,
                            SoLuongTon = 100,
                            TenSanPham = "Combo Gia Đình",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("FastFoodShop.Models.SanPhamCombo", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCombo", "MaSanPham");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamCombo");
                });

            modelBuilder.Entity("FastFoodShop.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("FastFoodShop.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodShop.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FastFoodShop.Models.DonHang", b =>
                {
                    b.HasOne("FastFoodShop.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("FastFoodShop.Models.SanPham", b =>
                {
                    b.HasOne("FastFoodShop.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("FastFoodShop.Models.SanPhamCombo", b =>
                {
                    b.HasOne("FastFoodShop.Models.SanPham", "Combo")
                        .WithMany("ComboChiTiet")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodShop.Models.SanPham", "SanPham")
                        .WithMany("SanPhamTrongCombo")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("FastFoodShop.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FastFoodShop.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("FastFoodShop.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FastFoodShop.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ComboChiTiet");

                    b.Navigation("SanPhamTrongCombo");
                });
#pragma warning restore 612, 618
        }
    }
}
